#!/bin/bash

TZ=EST

if [ $# -eq 0 ]; then
    year=$(date +%Y)
    day=$(date +%-d)
elif [ $# -eq 2 ]; then
    year=$1
    day=$2
else
    echo "Usage: $0 [year day]"
    exit 1
fi

if [ -d "$year/day$day" ]; then
    echo "Directory $year/day$day already exists"
    exit 1
fi
mkdir "$year/day$day/"
cp -n day.go.template "$year/day$day/day$day.go";
sed -i "s/\$\$\$year/$year/g; s/\$\$\$day/$day/g" "$year/day$day/day$day.go";
